name: Block requests to production domains
description: Adds configuration to /etc/hosts to stop tests accidentally reaching production
runs:
  using: "composite"
  steps:
  - shell: bash
    run: |
      if [ "$NOT_LINUX" == "true" ] ; then
        echo "Can't set /etc/hosts configuration on non-Linux runner"
        exit 1
      fi
      echo "203.0.113.0 logfire.dev" | sudo tee -a /etc/hosts
      echo "203.0.113.0 logfire-api.pydantic.dev" | sudo tee -a /etc/hosts
      echo "203.0.113.0 logfire.pydantic.dev" | sudo tee -a /etc/hosts
    env:
      NOT_LINUX: runner.os != 'linux'
