name: 🐛 Report a Platform Bug
description: Report a an issue with the rest of Logfire
labels: [Platform Bug]

body:
  - type: markdown
    attributes:
      value:  Thank you for contributing to Logfire! ✊

  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Please explain what you're seeing and what you would expect to see.

        Please provide as much detail as possible to make understanding and solving your problem as quick as possible. 🙏
    validations:
      required: true
