name: 🐛 Report an SDK Bug
description: Report a an issue with the Logfire SDK
labels: [SDK Bug]

body:
  - type: markdown
    attributes:
      value:  Thank you for contributing to Logfire! ✊

  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Please explain what you're seeing and what you would expect to see.

        Please provide as much detail as possible to make understanding and solving your problem as quick as possible. 🙏
    validations:
      required: true

  - type: textarea
    id: version
    attributes:
      label: Python, Logfire & OS Versions, related packages
      description: |
        Which version of Python & Logfire are you using, with which Operating System and with which OpenTelemetry packages?

        Don't worry if you can't run this command and don't have this information, we'll help you if we can.

        Please run the following command and copy the output below:

        ```bash
        logfire info
        ```

      render: TOML
