#!/usr/bin/env python3
"""Fake claude process for cassette-based testing.

Operates in two modes:
- **replay** (default): Reads a cassette file and replays recorded stdout
  messages, consuming stdin messages at the correct protocol points.
- **record**: Spawns the real `claude` CLI as a child process, proxies
  stdin/stdout between the SDK and the real process, and tees every
  message to a cassette file.

The cassette path and mode are controlled by environment variables:
- CASSETTE_PATH: path to the cassette JSON file (required)
- CASSETTE_MODE: "replay" (default) or "record"
- REAL_CLAUDE_PATH: path to the real claude CLI (required for record mode)

The SDK invokes this script via `ClaudeAgentOptions(cli_path=...)`.
All CLI arguments are accepted and ignored in replay mode (the SDK passes
flags like --output-format, --verbose, etc.).
"""

from __future__ import annotations

import json
import os
import subprocess
import sys
import threading

# cast is used inside functions, but __future__.annotations makes it lazy.
# We need it available at runtime for the recursive helpers.
from typing import cast


def main() -> None:
    # Handle version check: the SDK runs `cli_path -v` before the main session.
    if '-v' in sys.argv:
        cassette_path = os.environ.get('CASSETTE_PATH', '')
        if cassette_path and os.path.exists(cassette_path):
            with open(cassette_path) as f:
                cassette = json.load(f)
            version = cassette.get('metadata', {}).get('cli_version', '1.0.100')
        else:
            version = '1.0.100'
        print(version)
        return

    mode = os.environ.get('CASSETTE_MODE', 'replay')
    cassette_path = os.environ.get('CASSETTE_PATH', '')

    if not cassette_path:
        print('CASSETTE_PATH environment variable is required', file=sys.stderr)
        sys.exit(1)

    if mode == 'record':
        _record(cassette_path)
    else:
        _replay(cassette_path)


def _replay(cassette_path: str) -> None:
    """Replay recorded messages from a cassette file.

    Dynamic IDs (request_id, session_id, etc.) generated by the SDK at runtime
    won't match the cassette's recorded values. We track ID mappings from 'send'
    messages and patch 'recv' messages so the SDK sees its own IDs reflected back.
    """
    debug = os.environ.get('FAKE_CLAUDE_DEBUG', '')

    with open(cassette_path) as f:
        cassette = json.load(f)

    messages = cassette['messages']
    i = 0

    # Maps recorded IDs to live IDs (e.g., recorded request_id -> actual request_id)
    id_map: dict[str, str] = {}

    def _patch_ids(msg: object) -> object:
        """Recursively replace recorded IDs with live IDs in a message."""
        if isinstance(msg, dict):
            return {k: _patch_ids(v) for k, v in cast(dict[str, object], msg).items()}
        if isinstance(msg, list):
            return [_patch_ids(item) for item in cast(list[object], msg)]
        if isinstance(msg, str) and msg in id_map:
            return id_map[msg]
        return msg

    def _learn_ids(recorded: object, live: object) -> None:
        """Learn ID mappings by comparing recorded vs live 'send' messages."""
        if isinstance(recorded, dict) and isinstance(live, dict):
            rec_dict = cast(dict[str, object], recorded)
            live_dict = cast(dict[str, object], live)
            for key in rec_dict:
                if key in live_dict:
                    rec_val = rec_dict[key]
                    live_val = live_dict[key]
                    if isinstance(rec_val, str) and isinstance(live_val, str) and rec_val != live_val:
                        id_map[rec_val] = live_val
                    elif isinstance(rec_val, (dict, list)):
                        _learn_ids(cast(object, rec_val), live_val)
        elif isinstance(recorded, list) and isinstance(live, list):
            for rec_item, live_item in zip(cast(list[object], recorded), cast(list[object], live)):
                _learn_ids(rec_item, live_item)

    while i < len(messages):
        entry = messages[i]

        if entry['direction'] == 'recv':
            # The real CLI wrote this to stdout — replay it, with patched IDs
            msg = _patch_ids(entry['message'])
            line = json.dumps(msg) + '\n'
            if debug:
                print(f'[fake_claude] SEND stdout: {line.strip()[:120]}', file=sys.stderr)
            sys.stdout.write(line)
            sys.stdout.flush()
            i += 1

        elif entry['direction'] == 'send':
            # The SDK should write something to our stdin — consume it
            if debug:
                print(f'[fake_claude] WAIT stdin (entry {i})...', file=sys.stderr)
            line = sys.stdin.readline()
            if not line:
                if debug:
                    print('[fake_claude] stdin closed', file=sys.stderr)
                break
            if debug:
                print(f'[fake_claude] GOT stdin: {line.strip()[:120]}', file=sys.stderr)
            # Learn ID mappings from this message
            try:
                live_msg = json.loads(line)
                _learn_ids(entry['message'], live_msg)
            except json.JSONDecodeError:
                pass
            i += 1


def _record(cassette_path: str) -> None:
    """Record a real session by proxying between SDK and real claude CLI."""
    real_claude = os.environ.get('REAL_CLAUDE_PATH', '')
    if not real_claude:
        print('REAL_CLAUDE_PATH environment variable is required for record mode', file=sys.stderr)
        sys.exit(1)

    # Build the command: replace argv[0] with the real claude path,
    # keep all other arguments the SDK passed
    cmd = [real_claude] + sys.argv[1:]

    proc = subprocess.Popen(
        cmd,
        stdin=subprocess.PIPE,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )

    messages: list[dict[str, object]] = []
    cli_version = '1.0.100'  # Will be overridden if we can detect it

    def _proxy_stderr() -> None:
        """Pass stderr through without recording."""
        assert proc.stderr is not None
        for line in proc.stderr:
            sys.stderr.buffer.write(line)
            sys.stderr.buffer.flush()

    stderr_thread = threading.Thread(target=_proxy_stderr, daemon=True)
    stderr_thread.start()

    def _proxy_stdin() -> None:
        """Read from our stdin (SDK), forward to real process, record as 'send'."""
        assert proc.stdin is not None
        for line in sys.stdin:
            messages.append({'direction': 'send', 'message': json.loads(line)})
            proc.stdin.write(line.encode() if isinstance(line, str) else line)
            proc.stdin.flush()
        # stdin closed — close the child's stdin too
        proc.stdin.close()

    stdin_thread = threading.Thread(target=_proxy_stdin, daemon=True)
    stdin_thread.start()

    # Read stdout from real process, forward to SDK, record as 'recv'
    assert proc.stdout is not None
    for line_bytes in proc.stdout:
        line = line_bytes.decode()
        try:
            msg = json.loads(line)
            messages.append({'direction': 'recv', 'message': msg})
        except json.JSONDecodeError:
            # Non-JSON output — forward but don't record
            pass
        sys.stdout.write(line)
        sys.stdout.flush()

    proc.wait()
    stdin_thread.join(timeout=2)

    # Write cassette
    cassette = {
        'metadata': {
            'cli_version': cli_version,
        },
        'messages': messages,
    }
    with open(cassette_path, 'w') as f:
        json.dump(cassette, f, indent=2)
        f.write('\n')

    sys.exit(proc.returncode or 0)


if __name__ == '__main__':
    main()
