# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lf_otlp/profiles_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'lf_otlp/profiles_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from logfire._internal.profiling._proto import profiles_pb2 as lf__otlp_dot_profiles__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1elf_otlp/profiles_service.proto\x12\x11lf_otlp.collector\x1a\x16lf_otlp/profiles.proto\"\x97\x01\n\x1c\x45xportProfilesServiceRequest\x12=\n\x11resource_profiles\x18\x01 \x03(\x0b\x32\".lf_otlp.profiles.ResourceProfiles\x12\x38\n\ndictionary\x18\x02 \x01(\x0b\x32$.lf_otlp.profiles.ProfilesDictionary\"i\n\x1d\x45xportProfilesServiceResponse\x12H\n\x0fpartial_success\x18\x01 \x01(\x0b\x32/.lf_otlp.collector.ExportProfilesPartialSuccess\"P\n\x1c\x45xportProfilesPartialSuccess\x12\x19\n\x11rejected_profiles\x18\x01 \x01(\x03\x12\x15\n\rerror_message\x18\x02 \x01(\t2\x80\x01\n\x0fProfilesService\x12m\n\x06\x45xport\x12/.lf_otlp.collector.ExportProfilesServiceRequest\x1a\x30.lf_otlp.collector.ExportProfilesServiceResponse\"\x00\x42\xa6\x01\n\x14io.lf_otlp.collectorB\x14ProfilesServiceProtoP\x01Z?go.opentelemetry.io/proto/otlp/collector/profiles/v1development\xaa\x02\x34OpenTelemetry.Proto.Collector.Profiles.V1Developmentb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lf_otlp.profiles_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\024io.lf_otlp.collectorB\024ProfilesServiceProtoP\001Z?go.opentelemetry.io/proto/otlp/collector/profiles/v1development\252\0024OpenTelemetry.Proto.Collector.Profiles.V1Development'
  _globals['_EXPORTPROFILESSERVICEREQUEST']._serialized_start=78
  _globals['_EXPORTPROFILESSERVICEREQUEST']._serialized_end=229
  _globals['_EXPORTPROFILESSERVICERESPONSE']._serialized_start=231
  _globals['_EXPORTPROFILESSERVICERESPONSE']._serialized_end=336
  _globals['_EXPORTPROFILESPARTIALSUCCESS']._serialized_start=338
  _globals['_EXPORTPROFILESPARTIALSUCCESS']._serialized_end=418
  _globals['_PROFILESSERVICE']._serialized_start=421
  _globals['_PROFILESSERVICE']._serialized_end=549
# @@protoc_insertion_point(module_scope)
