"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2023, OpenTelemetry Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

This file includes work covered by the following copyright and permission notices:

Copyright 2016 Google Inc. All Rights Reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from opentelemetry.proto.common.v1 import common_pb2 as _common_pb2
from opentelemetry.proto.resource.v1 import resource_pb2 as _resource_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class ProfilesDictionary(_message.Message):
    """               Relationships Diagram

    ┌──────────────────┐                      LEGEND
    │   ProfilesData   │ ─────┐
    └──────────────────┘      │           ─────▶ embedded
      │                       │
      │ 1-n                   │           ─────▷ referenced by index
      ▼                       ▼
    ┌──────────────────┐   ┌────────────────────┐
    │ ResourceProfiles │   │ ProfilesDictionary │
    └──────────────────┘   └────────────────────┘
      │
      │ 1-n
      ▼
    ┌──────────────────┐
    │  ScopeProfiles   │
    └──────────────────┘
      │
      │ 1-n
      ▼
    ┌──────────────────┐
    │      Profile     │
    └──────────────────┘
      │                                n-1
      │ 1-n         ┌───────────────────────────────────────┐
      ▼             │                                       ▽
    ┌──────────────────┐   1-n   ┌─────────────────┐   ┌──────────┐
    │      Sample      │ ──────▷ │ KeyValueAndUnit │   │   Link   │
    └──────────────────┘         └─────────────────┘   └──────────┘
      │                              △      △
      │ n-1                          │      │ 1-n
      ▽                              │      │
    ┌──────────────────┐             │      │
    │      Stack       │             │      │
    └──────────────────┘             │      │
      │                     1-n      │      │
      │ 1-n         ┌────────────────┘      │
      ▽             │                       │
    ┌──────────────────┐   n-1   ┌─────────────┐
    │     Location     │ ──────▷ │   Mapping   │
    └──────────────────┘         └─────────────┘
      │
      │ 1-n
      ▼
    ┌──────────────────┐
    │       Line       │
    └──────────────────┘
      │
      │ 1-1
      ▽
    ┌──────────────────┐
    │     Function     │
    └──────────────────┘

    ProfilesDictionary represents the profiles data shared across the
    entire message being sent. The following applies to all fields in this
    message:

    - A dictionary is an array of dictionary items. Users of the dictionary
      compactly reference the items using the index within the array.

    - A dictionary MUST have a zero value encoded as the first element. This
      allows for _index fields pointing into the dictionary to use a 0 pointer
      value to indicate 'null' / 'not set'. Unless otherwise defined, a 'zero
      value' message value is one with all default field values, so as to
      minimize wire encoded size.

    - There SHOULD NOT be dupes in a dictionary. The identity of dictionary
      items is based on their value, recursively as needed. If a particular
      implementation does emit duplicated items, it MUST NOT attempt to give them
      meaning based on the index or order. A profile processor may remove
      duplicate items and this MUST NOT have any observable effects for
      consumers.

    - There SHOULD NOT be orphaned (unreferenced) items in a dictionary. A
      profile processor may remove ("garbage-collect") orphaned items and this
      MUST NOT have any observable effects for consumers.

    Status: [Alpha]
    """

    DESCRIPTOR: _descriptor.Descriptor

    MAPPING_TABLE_FIELD_NUMBER: _builtins.int
    LOCATION_TABLE_FIELD_NUMBER: _builtins.int
    FUNCTION_TABLE_FIELD_NUMBER: _builtins.int
    LINK_TABLE_FIELD_NUMBER: _builtins.int
    STRING_TABLE_FIELD_NUMBER: _builtins.int
    ATTRIBUTE_TABLE_FIELD_NUMBER: _builtins.int
    STACK_TABLE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def mapping_table(self) -> _containers.RepeatedCompositeFieldContainer[Global___Mapping]:
        """Mappings from address ranges to the image/binary/library mapped
        into that address range referenced by locations via Location.mapping_index.

        mapping_table[0] must always be zero value (Mapping{}) and present.
        """

    @_builtins.property
    def location_table(self) -> _containers.RepeatedCompositeFieldContainer[Global___Location]:
        """Locations referenced by samples via Stack.location_indices.

        location_table[0] must always be zero value (Location{}) and present.
        """

    @_builtins.property
    def function_table(self) -> _containers.RepeatedCompositeFieldContainer[Global___Function]:
        """Functions referenced by locations via Line.function_index.

        function_table[0] must always be zero value (Function{}) and present.
        """

    @_builtins.property
    def link_table(self) -> _containers.RepeatedCompositeFieldContainer[Global___Link]:
        """Links referenced by samples via Sample.link_index.

        link_table[0] must always be zero value (Link{}) and present.
        """

    @_builtins.property
    def string_table(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """A common table for strings referenced by various messages.

        string_table[0] must always be "" and present.
        """

    @_builtins.property
    def attribute_table(self) -> _containers.RepeatedCompositeFieldContainer[Global___KeyValueAndUnit]:
        """A common table for attributes referenced by the Profile, Sample, Mapping
        and Location messages below through attribute_indices field. Each entry is
        a key/value pair with an optional unit. Since this is a dictionary table,
        multiple entries with the same key may be present, unlike direct attribute
        tables like Resource.attributes. The referencing attribute_indices fields,
        though, do maintain the key uniqueness requirement.

        It's recommended to use attributes for variables with bounded cardinality,
        such as categorical variables
        (https://en.wikipedia.org/wiki/Categorical_variable). Using an attribute of
        a floating point type (e.g., CPU time) in a sample can quickly make every
        attribute value unique, defeating the purpose of the dictionary and
        impractically increasing the profile size.

        Examples of attributes:
            "/http/user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36"
            "abc.com/myattribute": true
            "allocation_size": 128 bytes

        attribute_table[0] must always be zero value (KeyValueAndUnit{}) and present.
        """

    @_builtins.property
    def stack_table(self) -> _containers.RepeatedCompositeFieldContainer[Global___Stack]:
        """Stacks referenced by samples via Sample.stack_index.

        stack_table[0] must always be zero value (Stack{}) and present.
        """

    def __init__(
        self,
        *,
        mapping_table: _abc.Iterable[Global___Mapping] | None = ...,
        location_table: _abc.Iterable[Global___Location] | None = ...,
        function_table: _abc.Iterable[Global___Function] | None = ...,
        link_table: _abc.Iterable[Global___Link] | None = ...,
        string_table: _abc.Iterable[_builtins.str] | None = ...,
        attribute_table: _abc.Iterable[Global___KeyValueAndUnit] | None = ...,
        stack_table: _abc.Iterable[Global___Stack] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["attribute_table", b"attribute_table", "function_table", b"function_table", "link_table", b"link_table", "location_table", b"location_table", "mapping_table", b"mapping_table", "stack_table", b"stack_table", "string_table", b"string_table"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ProfilesDictionary: _TypeAlias = ProfilesDictionary  # noqa: Y015

@_typing.final
class ProfilesData(_message.Message):
    """ProfilesData represents the profiles data that can be stored in persistent storage,
    OR can be embedded by other protocols that transfer OTLP profiles data but do not
    implement the OTLP protocol.

    The main difference between this message and collector protocol is that
    in this message there will not be any "control" or "metadata" specific to
    OTLP protocol.

    When new fields are added into this message, the OTLP request MUST be updated
    as well.

    Status: [Alpha]
    """

    DESCRIPTOR: _descriptor.Descriptor

    RESOURCE_PROFILES_FIELD_NUMBER: _builtins.int
    DICTIONARY_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def resource_profiles(self) -> _containers.RepeatedCompositeFieldContainer[Global___ResourceProfiles]:
        """An array of ResourceProfiles.
        For data coming from an SDK profiler, this array will typically contain one
        element. Host-level profilers will usually create one ResourceProfile per
        container, as well as one additional ResourceProfile grouping all samples
        from non-containerized processes.
        Other resource groupings are possible as well and clarified via
        Resource.attributes and semantic conventions.
        Tools that visualize profiles should prefer displaying
        resources_profiles[0].scope_profiles[0].profiles[0] by default.
        """

    @_builtins.property
    def dictionary(self) -> Global___ProfilesDictionary:
        """One instance of ProfilesDictionary"""

    def __init__(
        self,
        *,
        resource_profiles: _abc.Iterable[Global___ResourceProfiles] | None = ...,
        dictionary: Global___ProfilesDictionary | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["dictionary", b"dictionary"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["dictionary", b"dictionary", "resource_profiles", b"resource_profiles"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ProfilesData: _TypeAlias = ProfilesData  # noqa: Y015

@_typing.final
class ResourceProfiles(_message.Message):
    """A collection of ScopeProfiles from a Resource.

    Status: [Alpha]
    """

    DESCRIPTOR: _descriptor.Descriptor

    RESOURCE_FIELD_NUMBER: _builtins.int
    SCOPE_PROFILES_FIELD_NUMBER: _builtins.int
    SCHEMA_URL_FIELD_NUMBER: _builtins.int
    schema_url: _builtins.str
    """The Schema URL, if known. This is the identifier of the Schema that the resource data
    is recorded in. Notably, the last part of the URL path is the version number of the
    schema: http[s]://server[:port]/path/<version>. To learn more about Schema URL see
    https://opentelemetry.io/docs/specs/otel/schemas/#schema-url
    This schema_url applies to the data in the "resource" field. It does not apply
    to the data in the "scope_profiles" field which have their own schema_url field.
    """
    @_builtins.property
    def resource(self) -> _resource_pb2.Resource:
        """The resource for the profiles in this message.
        If this field is not set then no resource info is known.
        """

    @_builtins.property
    def scope_profiles(self) -> _containers.RepeatedCompositeFieldContainer[Global___ScopeProfiles]:
        """A list of ScopeProfiles that originate from a resource."""

    def __init__(
        self,
        *,
        resource: _resource_pb2.Resource | None = ...,
        scope_profiles: _abc.Iterable[Global___ScopeProfiles] | None = ...,
        schema_url: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["resource", b"resource"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["resource", b"resource", "schema_url", b"schema_url", "scope_profiles", b"scope_profiles"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ResourceProfiles: _TypeAlias = ResourceProfiles  # noqa: Y015

@_typing.final
class ScopeProfiles(_message.Message):
    """A collection of Profiles produced by an InstrumentationScope.

    Status: [Alpha]
    """

    DESCRIPTOR: _descriptor.Descriptor

    SCOPE_FIELD_NUMBER: _builtins.int
    PROFILES_FIELD_NUMBER: _builtins.int
    SCHEMA_URL_FIELD_NUMBER: _builtins.int
    schema_url: _builtins.str
    """The Schema URL, if known. This is the identifier of the Schema that the profile data
    is recorded in. Notably, the last part of the URL path is the version number of the
    schema: http[s]://server[:port]/path/<version>. To learn more about Schema URL see
    https://opentelemetry.io/docs/specs/otel/schemas/#schema-url
    This schema_url applies to the data in the "scope" field and all profiles in the
    "profiles" field.
    """
    @_builtins.property
    def scope(self) -> _common_pb2.InstrumentationScope:
        """The instrumentation scope information for the profiles in this message.
        Semantically when InstrumentationScope isn't set, it is equivalent with
        an empty instrumentation scope name (unknown).
        """

    @_builtins.property
    def profiles(self) -> _containers.RepeatedCompositeFieldContainer[Global___Profile]:
        """A list of Profiles that originate from an instrumentation scope."""

    def __init__(
        self,
        *,
        scope: _common_pb2.InstrumentationScope | None = ...,
        profiles: _abc.Iterable[Global___Profile] | None = ...,
        schema_url: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["scope", b"scope"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["profiles", b"profiles", "schema_url", b"schema_url", "scope", b"scope"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ScopeProfiles: _TypeAlias = ScopeProfiles  # noqa: Y015

@_typing.final
class Profile(_message.Message):
    """Profile is a common stacktrace profile format.

    Measurements represented with this format should follow the
    following conventions:

    - Consumers should treat unset optional fields as if they had been
      set with their default value.

    - When possible, measurements should be stored in "unsampled" form
      that is most useful to humans.  There should be enough
      information present to determine the original sampled values.

    - The profile is represented as a set of samples, where each sample
      references a stack trace which is a list of locations, each belonging
      to a mapping.
    - There is a N->1 relationship from Stack.location_indices entries to
      locations. For every Stack.location_indices entry there must be a
      unique Location with that index.
    - There is an optional N->1 relationship from locations to
      mappings. For every nonzero Location.mapping_id there must be a
      unique Mapping with that index.

    Represents a complete profile, including sample types, samples, mappings to
    binaries, stacks, locations, functions, string table, and additional
    metadata. It modifies and annotates pprof Profile with OpenTelemetry
    specific fields.

    Note that whilst fields in this message retain the name and field id from pprof in most cases
    for ease of understanding data migration, it is not intended that pprof:Profile and
    OpenTelemetry:Profile encoding be wire compatible.

    Status: [Alpha]
    """

    DESCRIPTOR: _descriptor.Descriptor

    SAMPLE_TYPE_FIELD_NUMBER: _builtins.int
    SAMPLES_FIELD_NUMBER: _builtins.int
    TIME_UNIX_NANO_FIELD_NUMBER: _builtins.int
    DURATION_NANO_FIELD_NUMBER: _builtins.int
    PERIOD_TYPE_FIELD_NUMBER: _builtins.int
    PERIOD_FIELD_NUMBER: _builtins.int
    PROFILE_ID_FIELD_NUMBER: _builtins.int
    DROPPED_ATTRIBUTES_COUNT_FIELD_NUMBER: _builtins.int
    ORIGINAL_PAYLOAD_FORMAT_FIELD_NUMBER: _builtins.int
    ORIGINAL_PAYLOAD_FIELD_NUMBER: _builtins.int
    ATTRIBUTE_INDICES_FIELD_NUMBER: _builtins.int
    time_unix_nano: _builtins.int
    """The following fields 3-12 are informational, do not affect
    interpretation of results.

    Time of collection. Value is UNIX Epoch time in nanoseconds since 00:00:00
    UTC on 1 January 1970.
    """
    duration_nano: _builtins.int
    """Duration of the profile. For instant profiles like live heap snapshot, the
    duration can be zero but it may be preferable to set time_unix_nano to the
    process start time and duration_nano to the relative time when the profile
    was gathered. This ensures Sample.timestamps_unix_nano values such as
    allocation timestamp fall into the profile time range.
    """
    period: _builtins.int
    """The number of events between sampled occurrences."""
    profile_id: _builtins.bytes
    """A globally unique identifier for a profile. The ID is a 16-byte array. An ID with
    all zeroes is considered invalid. It may be used for deduplication and signal
    correlation purposes. It is acceptable to treat two profiles with different values
    in this field as not equal, even if they represented the same object at an earlier
    time.
    This field is optional; an ID may be assigned to an ID-less profile in a later step.
    """
    dropped_attributes_count: _builtins.int
    """The number of attributes that were discarded. Attributes
    can be discarded because their keys are too long or because there are too many
    attributes. If this value is 0, then no attributes were dropped.
    """
    original_payload_format: _builtins.str
    """The original payload format. See also original_payload. Optional, but the
    format and the bytes must be set or unset together.

    The allowed values for the format string are defined by the OpenTelemetry
    specification. Some examples are "jfr", "pprof", "linux_perf".

    The original payload may be optionally provided when the conversion to the
    OLTP format was done from a different format with some loss of the fidelity
    and the receiver may want to store the original payload to allow future
    lossless export or reinterpretation. Some examples of the original format
    are JFR (Java Flight Recorder), pprof, Linux perf.

    Even when the original payload is in a format that is semantically close to
    OTLP, such as pprof, a conversion may still be lossy in some cases (e.g. if
    the pprof file contains custom extensions or conventions).

    The original payload can be large in size, so including the original
    payload should be configurable by the profiler or collector options. The
    default behavior should be to not include the original payload.
    """
    original_payload: _builtins.bytes
    """The original payload bytes. See also original_payload_format. Optional, but
    format and the bytes must be set or unset together.
    """
    @_builtins.property
    def sample_type(self) -> Global___ValueType:
        """The type and unit of all Sample.values in this profile.
        For a cpu or off-cpu profile this might be:
          ["cpu","nanoseconds"] or ["off_cpu","nanoseconds"]
        For a heap profile, this might be:
          ["allocated_objects","count"] or ["allocated_space","bytes"],
        """

    @_builtins.property
    def samples(self) -> _containers.RepeatedCompositeFieldContainer[Global___Sample]:
        """The set of samples recorded in this profile."""

    @_builtins.property
    def period_type(self) -> Global___ValueType:
        """The kind of events between sampled occurrences.
        e.g [ "cpu","cycles" ] or [ "heap","bytes" ]
        """

    @_builtins.property
    def attribute_indices(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]:
        """References to attributes in attribute_table. [optional]"""

    def __init__(
        self,
        *,
        sample_type: Global___ValueType | None = ...,
        samples: _abc.Iterable[Global___Sample] | None = ...,
        time_unix_nano: _builtins.int = ...,
        duration_nano: _builtins.int = ...,
        period_type: Global___ValueType | None = ...,
        period: _builtins.int = ...,
        profile_id: _builtins.bytes = ...,
        dropped_attributes_count: _builtins.int = ...,
        original_payload_format: _builtins.str = ...,
        original_payload: _builtins.bytes = ...,
        attribute_indices: _abc.Iterable[_builtins.int] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["period_type", b"period_type", "sample_type", b"sample_type"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["attribute_indices", b"attribute_indices", "dropped_attributes_count", b"dropped_attributes_count", "duration_nano", b"duration_nano", "original_payload", b"original_payload", "original_payload_format", b"original_payload_format", "period", b"period", "period_type", b"period_type", "profile_id", b"profile_id", "sample_type", b"sample_type", "samples", b"samples", "time_unix_nano", b"time_unix_nano"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Profile: _TypeAlias = Profile  # noqa: Y015

@_typing.final
class Link(_message.Message):
    """A pointer from a profile Sample to a trace Span.
    Connects a profile sample to a trace span, identified by unique trace and span IDs.

    Status: [Alpha]
    """

    DESCRIPTOR: _descriptor.Descriptor

    TRACE_ID_FIELD_NUMBER: _builtins.int
    SPAN_ID_FIELD_NUMBER: _builtins.int
    trace_id: _builtins.bytes
    """A unique identifier of a trace that this linked span is part of. The ID is a
    16-byte array.
    """
    span_id: _builtins.bytes
    """A unique identifier for the linked span. The ID is an 8-byte array."""
    def __init__(
        self,
        *,
        trace_id: _builtins.bytes = ...,
        span_id: _builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["span_id", b"span_id", "trace_id", b"trace_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Link: _TypeAlias = Link  # noqa: Y015

@_typing.final
class ValueType(_message.Message):
    """ValueType describes the type and units of a value.

    Status: [Alpha]
    """

    DESCRIPTOR: _descriptor.Descriptor

    TYPE_STRINDEX_FIELD_NUMBER: _builtins.int
    UNIT_STRINDEX_FIELD_NUMBER: _builtins.int
    type_strindex: _builtins.int
    """Index into ProfilesDictionary.string_table."""
    unit_strindex: _builtins.int
    """Index into ProfilesDictionary.string_table."""
    def __init__(
        self,
        *,
        type_strindex: _builtins.int = ...,
        unit_strindex: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["type_strindex", b"type_strindex", "unit_strindex", b"unit_strindex"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ValueType: _TypeAlias = ValueType  # noqa: Y015

@_typing.final
class Sample(_message.Message):
    """Each Sample records values encountered in some program context. The program
    context is typically a stack trace, perhaps augmented with auxiliary
    information like the thread-id, some indicator of a higher level request
    being handled etc.

    A Sample MUST have have at least one values or timestamps_unix_nano entry. If
    both fields are populated, they MUST contain the same number of elements, and
    the elements at the same index MUST refer to the same event.

    For the purposes of efficiently representing aggregated data observations, a Sample is regarded
    as having a shared identity and an associated collection of per-observation data points.
    Samples having the same identity SHOULD be combined by inserting timestamps and values to the data arrays.

    Examples of different ways ('shapes') of representing a sample with the total value of 10:

    Report of a stacktrace at 10 timestamps (consumers must assume the value is 1 for each point):
       values: []
       timestamps_unix_nano: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

    Report of a stacktrace with an aggregated value without timestamps:
      values: [10]
       timestamps_unix_nano: []

    Report of a stacktrace at 4 timestamps where each point records a specific value:
       values: [2, 2, 3, 3]
       timestamps_unix_nano: [1, 2, 3, 4]

    All Samples for a Profile SHOULD have the same shape, i.e. all data observation series should consistently
    adopt the same data recording style.

    Status: [Alpha]
    """

    DESCRIPTOR: _descriptor.Descriptor

    STACK_INDEX_FIELD_NUMBER: _builtins.int
    ATTRIBUTE_INDICES_FIELD_NUMBER: _builtins.int
    LINK_INDEX_FIELD_NUMBER: _builtins.int
    VALUES_FIELD_NUMBER: _builtins.int
    TIMESTAMPS_UNIX_NANO_FIELD_NUMBER: _builtins.int
    stack_index: _builtins.int
    """A Sample's identity (i.e. 'primary key') is the tuple of {stack_index, set_of(attribute_indices), link_index}

    Reference to stack in ProfilesDictionary.stack_table.
    """
    link_index: _builtins.int
    """Reference to link in ProfilesDictionary.link_table. [optional]
    It can be unset / set to 0 if no link exists, as link_table[0] is always a 'null' default value.
    """
    @_builtins.property
    def attribute_indices(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]:
        """References to attributes in ProfilesDictionary.attribute_table. [optional]"""

    @_builtins.property
    def values(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]:
        """The following fields may contain per-observation data and do not form part of the Sample's identity.

        The type and unit of each value is defined by Profile.sample_type.
        """

    @_builtins.property
    def timestamps_unix_nano(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]:
        """Timestamps associated with Sample. Value is UNIX Epoch time in nanoseconds
        since 00:00:00 UTC on 1 January 1970. The timestamps should fall within the
        [Profile.time_unix_nano, Profile.time_unix_nano + Profile.duration_nano)
        time range.
        """

    def __init__(
        self,
        *,
        stack_index: _builtins.int = ...,
        attribute_indices: _abc.Iterable[_builtins.int] | None = ...,
        link_index: _builtins.int = ...,
        values: _abc.Iterable[_builtins.int] | None = ...,
        timestamps_unix_nano: _abc.Iterable[_builtins.int] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["attribute_indices", b"attribute_indices", "link_index", b"link_index", "stack_index", b"stack_index", "timestamps_unix_nano", b"timestamps_unix_nano", "values", b"values"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Sample: _TypeAlias = Sample  # noqa: Y015

@_typing.final
class Mapping(_message.Message):
    """Describes the mapping of a binary in memory, including its address range,
    file offset, and metadata like build ID

    Status: [Alpha]
    """

    DESCRIPTOR: _descriptor.Descriptor

    MEMORY_START_FIELD_NUMBER: _builtins.int
    MEMORY_LIMIT_FIELD_NUMBER: _builtins.int
    FILE_OFFSET_FIELD_NUMBER: _builtins.int
    FILENAME_STRINDEX_FIELD_NUMBER: _builtins.int
    ATTRIBUTE_INDICES_FIELD_NUMBER: _builtins.int
    memory_start: _builtins.int
    """Address at which the binary (or DLL) is loaded into memory."""
    memory_limit: _builtins.int
    """The limit of the address range occupied by this mapping."""
    file_offset: _builtins.int
    """Offset in the binary that corresponds to the first mapped address."""
    filename_strindex: _builtins.int
    """The object this entry is loaded from.  This can be a filename on
    disk for the main binary and shared libraries, or virtual
    abstractions like "[vdso]".
    Index into ProfilesDictionary.string_table.
    """
    @_builtins.property
    def attribute_indices(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]:
        """References to attributes in ProfilesDictionary.attribute_table. [optional]"""

    def __init__(
        self,
        *,
        memory_start: _builtins.int = ...,
        memory_limit: _builtins.int = ...,
        file_offset: _builtins.int = ...,
        filename_strindex: _builtins.int = ...,
        attribute_indices: _abc.Iterable[_builtins.int] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["attribute_indices", b"attribute_indices", "file_offset", b"file_offset", "filename_strindex", b"filename_strindex", "memory_limit", b"memory_limit", "memory_start", b"memory_start"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Mapping: _TypeAlias = Mapping  # noqa: Y015

@_typing.final
class Stack(_message.Message):
    """A Stack represents a stack trace as a list of locations.

    Status: [Alpha]
    """

    DESCRIPTOR: _descriptor.Descriptor

    LOCATION_INDICES_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def location_indices(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]:
        """References to locations in ProfilesDictionary.location_table.
        The first location is the leaf frame.
        """

    def __init__(
        self,
        *,
        location_indices: _abc.Iterable[_builtins.int] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["location_indices", b"location_indices"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Stack: _TypeAlias = Stack  # noqa: Y015

@_typing.final
class Location(_message.Message):
    """Describes function and line table debug information.

    Status: [Alpha]
    """

    DESCRIPTOR: _descriptor.Descriptor

    MAPPING_INDEX_FIELD_NUMBER: _builtins.int
    ADDRESS_FIELD_NUMBER: _builtins.int
    LINES_FIELD_NUMBER: _builtins.int
    ATTRIBUTE_INDICES_FIELD_NUMBER: _builtins.int
    mapping_index: _builtins.int
    """Reference to mapping in ProfilesDictionary.mapping_table.
    It can be unset / set to 0 if the mapping is unknown or not applicable for
    this profile type, as mapping_table[0] is always a 'null' default mapping.
    """
    address: _builtins.int
    """The instruction address for this location, if available.  It
    should be within [Mapping.memory_start...Mapping.memory_limit]
    for the corresponding mapping. A non-leaf address may be in the
    middle of a call instruction. It is up to display tools to find
    the beginning of the instruction if necessary.
    """
    @_builtins.property
    def lines(self) -> _containers.RepeatedCompositeFieldContainer[Global___Line]:
        """Multiple line indicates this location has inlined functions,
        where the last entry represents the caller into which the
        preceding entries were inlined.

        E.g., if memcpy() is inlined into printf:
           lines[0].function_name == "memcpy"
           lines[1].function_name == "printf"
        """

    @_builtins.property
    def attribute_indices(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]:
        """References to attributes in ProfilesDictionary.attribute_table. [optional]"""

    def __init__(
        self,
        *,
        mapping_index: _builtins.int = ...,
        address: _builtins.int = ...,
        lines: _abc.Iterable[Global___Line] | None = ...,
        attribute_indices: _abc.Iterable[_builtins.int] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["address", b"address", "attribute_indices", b"attribute_indices", "lines", b"lines", "mapping_index", b"mapping_index"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Location: _TypeAlias = Location  # noqa: Y015

@_typing.final
class Line(_message.Message):
    """Details a specific line in a source code, linked to a function.

    Status: [Alpha]
    """

    DESCRIPTOR: _descriptor.Descriptor

    FUNCTION_INDEX_FIELD_NUMBER: _builtins.int
    LINE_FIELD_NUMBER: _builtins.int
    COLUMN_FIELD_NUMBER: _builtins.int
    function_index: _builtins.int
    """Reference to function in ProfilesDictionary.function_table."""
    line: _builtins.int
    """Line number in source code. 0 means unset."""
    column: _builtins.int
    """Column number in source code. 0 means unset."""
    def __init__(
        self,
        *,
        function_index: _builtins.int = ...,
        line: _builtins.int = ...,
        column: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["column", b"column", "function_index", b"function_index", "line", b"line"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Line: _TypeAlias = Line  # noqa: Y015

@_typing.final
class Function(_message.Message):
    """Describes a function, including its human-readable name, system name,
    source file, and starting line number in the source.

    Status: [Alpha]
    """

    DESCRIPTOR: _descriptor.Descriptor

    NAME_STRINDEX_FIELD_NUMBER: _builtins.int
    SYSTEM_NAME_STRINDEX_FIELD_NUMBER: _builtins.int
    FILENAME_STRINDEX_FIELD_NUMBER: _builtins.int
    START_LINE_FIELD_NUMBER: _builtins.int
    name_strindex: _builtins.int
    """The function name. Empty string if not available."""
    system_name_strindex: _builtins.int
    """Function name, as identified by the system. For instance,
    it can be a C++ mangled name. Empty string if not available.
    """
    filename_strindex: _builtins.int
    """Source file containing the function. Empty string if not available."""
    start_line: _builtins.int
    """Line number in source file. 0 means unset."""
    def __init__(
        self,
        *,
        name_strindex: _builtins.int = ...,
        system_name_strindex: _builtins.int = ...,
        filename_strindex: _builtins.int = ...,
        start_line: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["filename_strindex", b"filename_strindex", "name_strindex", b"name_strindex", "start_line", b"start_line", "system_name_strindex", b"system_name_strindex"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Function: _TypeAlias = Function  # noqa: Y015

@_typing.final
class KeyValueAndUnit(_message.Message):
    """A custom 'dictionary native' style of encoding attributes which is more convenient
    for profiles than opentelemetry.proto.common.v1.KeyValue
    Specifically, uses the string table for keys and allows optional unit information.

    Status: [Alpha]
    """

    DESCRIPTOR: _descriptor.Descriptor

    KEY_STRINDEX_FIELD_NUMBER: _builtins.int
    VALUE_FIELD_NUMBER: _builtins.int
    UNIT_STRINDEX_FIELD_NUMBER: _builtins.int
    key_strindex: _builtins.int
    """The index into the string table for the attribute's key."""
    unit_strindex: _builtins.int
    """The index into the string table for the attribute's unit.
    zero indicates implicit (by semconv) or non-defined unit.
    """
    @_builtins.property
    def value(self) -> _common_pb2.AnyValue:
        """The value of the attribute."""

    def __init__(
        self,
        *,
        key_strindex: _builtins.int = ...,
        value: _common_pb2.AnyValue | None = ...,
        unit_strindex: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["key_strindex", b"key_strindex", "unit_strindex", b"unit_strindex", "value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___KeyValueAndUnit: _TypeAlias = KeyValueAndUnit  # noqa: Y015
