"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2023, OpenTelemetry Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from logfire._internal.profiling._proto import profiles_pb2 as _profiles_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class ExportProfilesServiceRequest(_message.Message):
    """Status: [Alpha]"""

    DESCRIPTOR: _descriptor.Descriptor

    RESOURCE_PROFILES_FIELD_NUMBER: _builtins.int
    DICTIONARY_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def resource_profiles(self) -> _containers.RepeatedCompositeFieldContainer[_profiles_pb2.ResourceProfiles]:
        """An array of ResourceProfiles.
        For data coming from a single resource this array will typically contain one
        element. Intermediary nodes (such as OpenTelemetry Collector) that receive
        data from multiple origins typically batch the data before forwarding further and
        in that case this array will contain multiple elements.
        """

    @_builtins.property
    def dictionary(self) -> _profiles_pb2.ProfilesDictionary:
        """The reference table containing all data shared by profiles across the message being sent."""

    def __init__(
        self,
        *,
        resource_profiles: _abc.Iterable[_profiles_pb2.ResourceProfiles] | None = ...,
        dictionary: _profiles_pb2.ProfilesDictionary | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["dictionary", b"dictionary"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["dictionary", b"dictionary", "resource_profiles", b"resource_profiles"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ExportProfilesServiceRequest: _TypeAlias = ExportProfilesServiceRequest  # noqa: Y015

@_typing.final
class ExportProfilesServiceResponse(_message.Message):
    """Status: [Alpha]"""

    DESCRIPTOR: _descriptor.Descriptor

    PARTIAL_SUCCESS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def partial_success(self) -> Global___ExportProfilesPartialSuccess:
        """The details of a partially successful export request.

        If the request is only partially accepted
        (i.e. when the server accepts only parts of the data and rejects the rest)
        the server MUST initialize the `partial_success` field and MUST
        set the `rejected_<signal>` with the number of items it rejected.

        Servers MAY also make use of the `partial_success` field to convey
        warnings/suggestions to senders even when the request was fully accepted.
        In such cases, the `rejected_<signal>` MUST have a value of `0` and
        the `error_message` MUST be non-empty.

        A `partial_success` message with an empty value (rejected_<signal> = 0 and
        `error_message` = "") is equivalent to it not being set/present. Senders
        SHOULD interpret it the same way as in the full success case.
        """

    def __init__(
        self,
        *,
        partial_success: Global___ExportProfilesPartialSuccess | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["partial_success", b"partial_success"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["partial_success", b"partial_success"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ExportProfilesServiceResponse: _TypeAlias = ExportProfilesServiceResponse  # noqa: Y015

@_typing.final
class ExportProfilesPartialSuccess(_message.Message):
    """Status: [Alpha]"""

    DESCRIPTOR: _descriptor.Descriptor

    REJECTED_PROFILES_FIELD_NUMBER: _builtins.int
    ERROR_MESSAGE_FIELD_NUMBER: _builtins.int
    rejected_profiles: _builtins.int
    """The number of rejected profiles.

    A `rejected_<signal>` field holding a `0` value indicates that the
    request was fully accepted.
    """
    error_message: _builtins.str
    """A developer-facing human-readable message in English. It should be used
    either to explain why the server rejected parts of the data during a partial
    success or to convey warnings/suggestions during a full success. The message
    should offer guidance on how users can address such issues.

    error_message is an optional field. An error_message with an empty value
    is equivalent to it not being set.
    """
    def __init__(
        self,
        *,
        rejected_profiles: _builtins.int = ...,
        error_message: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["error_message", b"error_message", "rejected_profiles", b"rejected_profiles"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ExportProfilesPartialSuccess: _TypeAlias = ExportProfilesPartialSuccess  # noqa: Y015
