name: Actionlint

on:
  push:
    paths:
      - '.github/workflows/**'
      - '.github/actionlint.yaml'
      - '.github/actionlint.yml'
  pull_request:
    paths:
      - '.github/workflows/**'
      - '.github/actionlint.yaml'
      - '.github/actionlint.yml'

permissions:
  contents: read

concurrency:
  group: actionlint-${{ github.ref }}
  cancel-in-progress: true

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          persist-credentials: false
      - name: Download actionlint
        id: download
        run: bash <(curl -sSf https://raw.githubusercontent.com/rhysd/actionlint/v1.7.7/scripts/download-actionlint.bash) 1.7.7
        shell: bash
      - name: Run actionlint
        run: |
          ./actionlint -color
        shell: bash
